[[main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1
[[main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 2
[[main]]
	identifier = "portfolio"
	name = "Portfolio"
	url = "/portfolio/"
	weight = 3
[[main]]
	identifier = "pricing"
	name = "Pricing"
	url = "/pricing/"
	weight = 4
[[main]]
	identifier = "contact"
	name = "Contact"
	url = "/contact/"
	weight = 5