baseURL = "https://symulamedia.com"
languageCode = "en-us"
title = "Symula Media Group"
theme = "github.com/willfaught/paige"
timeout = "300s"

[[module.imports]]
path = "github.com/willfaught/paige"

##### Header Menu Nav
[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

#[[languages.en.menu.main]]
#identifier = "services"
#name = "Services"
#url = "/services/"
#weight = 30

#[[languages.en.menu.main]]
#identifier = "aerial"
#name = "Aerial"
#parent = "services"
#url = "/services/aerial/"
#weight = 10

[[languages.en.menu.main]]
identifier = "realEstate"
name = "Real Estate"
#parent = "services"
url = "/realEstate/"
weight = 30

[[languages.en.menu.main]]
identifier = "matterport"
name = "Matterport 3D"
#parent = "services"
url = "/matterport/"
weight = 40
#
#[[languages.en.menu.main]]
#identifier = "weddings"
#name = "Weddings"
#parent = "services"
#url = "/services/weddings/"
#weight = 40
#
#[[languages.en.menu.main]]
#identifier = "engagements"
#name = "Engagements"
#parent = "services"
#url = "/services/engagements/"
#weight = 50

[[languages.en.menu.main]]
identifier = "pricing"
name = "Pricing"
url = "/pricing"
weight = 40

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 50

##############################
# Theme Configuration
# see https://github.com/willfaught/paige
##############################

[paige]
color = "#9FB0B3" # Bootstrap primary color and theme color for Safari and Windows
math = true # Enable math typesetting
style = "" # CSS included at the end of the stylesheet, before style-last.css

[paige.analytics]
disable = true # Disable all analytics

[paige.analytics.chartbeat] # See https://chartbeat.com
account_id = ""
domain = ""

[paige.analytics.clicky] # See https://clicky.com
account_id = ""

[paige.analytics.fathom] # See https://usefathom.com
account_id = ""

[paige.analytics.finteza] # See https://finteza.com
account_id = ""
script_url = ""

[paige.analytics.hotjar] # See https://hotjar.com
account_id = ""

[paige.analytics.matomo] # See https://matomo.org
account_id = ""
host_url = ""

[paige.analytics.mixpanel] # See https://mixpanel.com
token = ""

[paige.analytics.plausible] # See https://plausible.io
account_id = ""

[paige.analytics.woopra] # See https://woopra.com
domain = ""

[paige.analytics.yandex] # See https://metrica.yandex.com
account_id = ""

[paige.comments]
disable = true # Disable all comments

[paige.date]
format = ":date_long" # Hugo date format

[paige.git]
commit_url = "" # Example is "https://github.com/willfaught/paige/commit/%s"

[paige.menu]
breakpoint = "sm" # Bootstrap breakpoint at which to display all menu items
style = "tabs" # Must be "links", "pills", "tabs", or "underline"

[paige.rss]
hide_page = true
managing_editor = ""
web_master = ""

[paige.search]
hide_page = true

[authors.symula-media-group]
name = "Symula Media Group"
default = true # Credit this author in pages that have no authors parameter
